USE ROLE SECURITYADMIN;
GRANT ROLE SWEDAVIA_DLT_ROLE TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
USE WAREHOUSE SWEDAVIA_WH;
SHOW TABLES IN SCHEMA FLIGHT_DB.STAGING;


SELECT COUNT(*) AS antal_flyg
FROM FLIGHT_DB.STAGING.FLIGHTS;

SELECT airport, direction, COUNT(*) AS antal
FROM FLIGHT_DB.STAGING.FLIGHTS
GROUP BY airport, direction
ORDER BY airport, direction;


DESCRIBE TABLE FLIGHT_DB.STAGING.FLIGHTS;

SELECT *
FROM FLIGHT_DB.STAGING.FLIGHTS
LIMIT 5;




USE ROLE SYSADMIN;
USE WAREHOUSE SWEDAVIA_WH;

SHOW TABLES IN SCHEMA FLIGHT_DB.STAGING;

SELECT COUNT(*) AS antal_flygplatser FROM FLIGHT_DB.STAGING.AIRPORTS;
SELECT COUNT(*) AS antal_flygbolag FROM FLIGHT_DB.STAGING.AIRLINES;