-- Create a dedicated role for the dlt pipeline
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS SWEDAVIA_DLT_ROLE;

-- Grant permissions to the role
USE ROLE ACCOUNTADMIN;

GRANT USAGE ON WAREHOUSE SWEDAVIA_WH
TO ROLE SWEDAVIA_DLT_ROLE;

GRANT USAGE ON DATABASE FLIGHT_DB
TO ROLE SWEDAVIA_DLT_ROLE;

GRANT USAGE ON SCHEMA FLIGHT_DB.STAGING
TO ROLE SWEDAVIA_DLT_ROLE;

GRANT CREATE TABLE ON SCHEMA FLIGHT_DB.STAGING
TO ROLE SWEDAVIA_DLT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA FLIGHT_DB.STAGING
TO ROLE SWEDAVIA_DLT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA FLIGHT_DB.STAGING
TO ROLE SWEDAVIA_DLT_ROLE;

-- Verify role grants
SHOW GRANTS TO ROLE SWEDAVIA_DLT_ROLE;

USE ROLE ACCOUNTADMIN;

GRANT CREATE SCHEMA ON DATABASE FLIGHT_DB TO ROLE SWEDAVIA_DLT_ROLE;