CREATE WAREHOUSE IF NOT EXISTS SWEDAVIA_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE; 


CREATE DATABASE IF NOT EXISTS FLIGHT_DB;

CREATE SCHEMA IF NOT EXISTS FLIGHT_DB.STAGING;


SHOW WAREHOUSES LIKE 'SWEDAVIA_WH';

SHOW DATABASES LIKE 'FLIGHT_DB';

SHOW SCHEMAS IN DATABASE FLIGHT_DB;

USE ROLE SYSADMIN;

USE WAREHOUSE SWEDAVIA_WH;

USE DATABASE FLIGHT_DB;

USE SCHEMA STAGING;
